// let obj={{Instagram:"https://instagram.com/anayshaa1312?igshid=YmMyMTA2M2Y=",

// Github:"https://github.com/Gitkita",

// LinkedIn:"https://www.linkedin.com/in/ankita-sahu-19a66820b"}}
let allskills = {
  0: "HTML",
  1: "CSS",
  2: "Javascript",
  3: "PHP",
  4: "Python",
  5: "ReactJS",
  6: "C",
  7: "C#",
  8: "C++",
  9: "MongoDB",
  10: "Java",
  11: "Flutter",
  12: "React Native",
  13: "Kotlin",
  14: "Express",
  15: "NodeJS",
  16: "Django",
  17: "Flask",
  18: "Photoshop",
  19: "Figma",
  20: "Canva",
  21: "After Effects",
  22: "Premier Pro",
  23: "Filmora",
  24: "Angular",
  25: "NextJs",
  26: "Firebase",
  27: "E Press",
  28: "Redux",
  29: "Unity",
  30: "Vuforia",
  31: "Prolog",
  32: "WordPress",
  33: "Ajax",
  34: "RegEx",
  35: "MySQL",
  36: "J Query",
  37: "DBMS",
};
const stuinfo = {
  0: {
    name: "Pranav Soan",
    Instagram: "https://instagram.com/_.prxnxv__?igshid=YmMyMTA2M2Y=",
    Skills: [0, 1, 2, 5, 6, 8, 19, 20, 23, 35],
    Github: "https://github.com/pranavv444",
    LinkedIn: "https://www.linkedin.com/in/pranav-soan-b67675214/",
  },
  1: {
    name: "Rishabh Dubey",
    Instagram: "https://instagram.com/dubeyrishabh101?igshid=YmMyMTA2M2Y=",
    Skills: [0, 1, 2, 5, 6, 8, 19, 20, 23, 35],
    Github: "https://github.com/pranavv444",
    LinkedIn: "https://www.linkedin.com/in/pranav-soan-b67675214/",
  },
  2: {
    name: "Shivansh Mehta",
    Instagram: "https://www.instagram.com/_shivansh.mehta_/",
    Skills: [0, 1, 2, 4, 6, 8, 16, 17],
    Github: "https://github.com/ShivanshMehtaa",
    LinkedIn: "https://www.linkedin.com/in/shivansh-mehta-399427226/",
  },
  3: {
    name: "Shivansh Jasathy",
    Instagram: "https://instagram.com/shivansh_jasathy?igshid=YmMyMTA2M2Y=",
    Skills: [4, 6, 8, 11, 13],
    Github: "https://github.com/Shivxnshjasathi",
    LinkedIn: "https://www.linkedin.com/in/shivansh-jasathi-5095a3225",
  },
  4: {
    name: "Harsh Multani",
    Instagram: "",
    Skills: [0, 1, 8],
    Github: "https://github.com/HarshMultani/HarshMultani.github.io",
    LinkedIn: "https://www.linkedin.com/in/harsh-multani-268501225",
  },
  5: {
    name: "Shivansh Upadhyay",
    Instagram: "https://www.instagram.com/aslishivansh/",
    Skills: [0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 14, 15, 24, 29, 30, 31],
    Github: "https://github.com/wh0shivansh",
    LinkedIn: "https://www.linkedin.com/in/shivansh-upadhyay-bb594a240",
  },
  6: {
    name: "Danish Ali",
    Instagram: "https://instagram.com/x.big_achiever.x",
    Skills: [4, 8],
    Github: "https://github.com/BigAchiever",
    LinkedIn: "https://www.linkedin.com/in/big-achiever",
  },
  7: {
    name: "Vedika Singh",
    Instagram: "https://instagram.com/ved.ika_15_",
    Skills: [0, 1, 2, 8, 10],
    Github: "https://github.com/vedika1523",
    LinkedIn: "https://www.linkedin.com/in/vedika-singh-078276229",
  },
  8: {
    name: "Ankita Sahu",
    Instagram: "https://instagram.com/anayshaa1312?igshid=YmMyMTA2M2Y=",
    Skills: [6, 8, 10],
    Github: "https://github.com/Gitkita",
    LinkedIn: "https://www.linkedin.com/in/ankita-sahu-19a66820b",
  },
  9: {
    name: "Pramod Aswani",
    Instagram: "https://www.instagram.com/pramodaswani10/",
    Skills: [0, 1, 6, 8],
    Github: "https://github.com/Pramod-Aswani1012",
    LinkedIn: "https://www.linkedin.com/in/pramod-aswani-442146222/",
  },
  10: {
    name: "Anushri Shrivastava",
    Instagram: "",
    Skills: [1, 4, 8, 35],
    Github: "https://github.com/Anu-shri",
    LinkedIn: "https://www.linkedin.com/in/anushri-shrivastava-710622225",
  },
  11: {
    name: "Ayush Jain",
    Instagram: "https://www.instagram.com/a.ayush_09/",
    Skills: [0, 1, 2, 4, 6, 8],
    Github: "https://github.com/AayushJain09",
    LinkedIn: "https://www.linkedin.com/in/aayush-jain-125334225",
  },
  12: {
    name: "Prince Raghuvanshi",
    Instagram: "",
    Skills: [8],
    Github: "https://github.com/princeragh1801",
    LinkedIn: "https://www.linkedin.com/in/prince-raghuwanshi-b4a3541b1",
  },
  13: {
    name: "Ankit Gupta",
    Instagram: "https://www.instagram.com/a.ayush_09/",
    Skills: [],
    Github: "https://github.com/AayushJain09",
    LinkedIn: "https://www.linkedin.com/in/aayush-jain-125334225",
  },
  14: {
    name: "Palak Jaiswal",
    Instagram: "https://instagram.com/_p.jais_?igshid=YmMyMTA2M2Y=",
    Skills: [4, 6, 37],
    Github: "https://github.com/palakjaiswal16",
    LinkedIn: "https://www.linkedin.com/in/palak-jaiswal-1515a5225",
  },
};
const foundersinfo = {
  1: {
    name: "Harshal Jain",
    Instagram: "https://instagram.com/harshal_3011?igshid=YmMyMTA2M2Y=",
    Skills: [0, 1, 2, 5, 9, 12, 27, 15, 18, 19, 20, 21, 23, 24, 25, 26, 28],
    Github: "https://github.com/virajj014?tab=repositories",
    LinkedIn: "https://www.linkedin.com/in/harshal-jain-5742b1199/",
  },
  2: {
    name: "Amogh Saxena",
    Instagram: "https://instagram.com/amogh_2409?igshid=YmMyMTA2M2Y=",
    Skills: [
      0, 1, 2, 3, 4, 5, 9, 10, 11, 13, 14, 16, 17, 18, 19, 20, 21, 22, 23, 26,
    ],
    Github: "https://github.com/Amogh24094",
    LinkedIn: "https://www.linkedin.com/in/amoghsaxena24",
  },
};
